#!/bin/bash
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
BINARY="$PROJECT_ROOT/dist/cmd2host"
PORT=19876
PASSED=0
FAILED=0

# Token authentication for tests (must be 64 hex chars to pass format validation)
TEST_TOKEN="0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
# Pre-calculated BLAKE3 hash of TEST_TOKEN
# Generated by: echo -n "$TEST_TOKEN" | cmd2host --hash-token
# If hashToken implementation changes (e.g., different algorithm), regenerate this value
TEST_TOKEN_HASH="b12d91bcebcbecea463bbd02edb632317f0e50c80f1bfa54204a7aee68baf857"
TOKEN_DIR="$HOME/.cmd2host/tokens"

# Project config setup
PROJECT_ID="taisukeoe_cmd2host"
PROJECT_DIR="$HOME/.cmd2host/projects/$PROJECT_ID"
DAEMON_CONFIG_DIR="$HOME/.cmd2host"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

cleanup() {
    if [[ -n "${DAEMON_PID:-}" ]]; then
        kill "$DAEMON_PID" 2>/dev/null || true
        wait "$DAEMON_PID" 2>/dev/null || true
    fi
    # Clean up test token (with safety checks)
    if [[ -n "$TOKEN_DIR" && -n "$TEST_TOKEN_HASH" && "$TOKEN_DIR" == *".cmd2host/tokens" ]]; then
        rm -f "$TOKEN_DIR/$TEST_TOKEN_HASH"
    fi
    # Clean up test project config (with safety checks)
    if [[ -n "$PROJECT_DIR" && "$PROJECT_DIR" == *".cmd2host/projects/"* ]]; then
        rm -rf "$PROJECT_DIR"
    fi
    # Clean up test daemon config (with safety checks)
    if [[ -n "$DAEMON_CONFIG_DIR" && "$DAEMON_CONFIG_DIR" == *".cmd2host" ]]; then
        rm -f "$DAEMON_CONFIG_DIR/daemon.json"
    fi
    # Clean up workspace_path integration probe artifacts (with safety checks)
    if [[ -n "${PROJECT_ROOT:-}" && "$PROJECT_ROOT" == */cmd2host* ]]; then
        rm -rf "$PROJECT_ROOT/test/host/scratch" 2>/dev/null || true
        rm -rf "$PROJECT_ROOT/.cmd2host-staging" 2>/dev/null || true
    fi
}
trap cleanup EXIT

setup_test_token() {
    mkdir -p "$TOKEN_DIR"
    # Token file contains JSON with repo data (bound at token generation time)
    echo -n '{"repo":"taisukeoe/cmd2host"}' > "$TOKEN_DIR/$TEST_TOKEN_HASH"
}

setup_daemon_config() {
    mkdir -p "$DAEMON_CONFIG_DIR"
    # Create daemon config with test port
    cat > "$DAEMON_CONFIG_DIR/daemon.json" <<EOF
{
  "listen_address": "127.0.0.1",
  "listen_port": $PORT
}
EOF
}

setup_project_config() {
    mkdir -p "$PROJECT_DIR"
    # Create project config with operations
    cat > "$PROJECT_DIR/config.json" <<EOF
{
  "repo": "taisukeoe/cmd2host",
  "repo_path": "$PROJECT_ROOT",
  "allowed_operations": ["gh_pr_view", "gh_pr_list", "gh_version", "ws_write", "ws_write_recursive", "git_add"],
  "constraints": {
    "path_deny": [".env*", "**/*.pem"]
  },
  "operations": {
    "gh_version": {
      "command": "gh",
      "args_template": ["--version"],
      "params": {},
      "description": "Show gh CLI version"
    },
    "gh_pr_view": {
      "command": "gh",
      "args_template": ["pr", "view", "{number}", "-R", "{repo}"],
      "params": {
        "number": {"type": "integer", "min": 1}
      },
      "allowed_flags": ["--json"],
      "description": "View a pull request"
    },
    "gh_pr_list": {
      "command": "gh",
      "args_template": ["pr", "list", "-R", "{repo}"],
      "params": {},
      "allowed_flags": ["--json", "--state", "--limit"],
      "description": "List pull requests"
    },
    "ws_write": {
      "command": "dd",
      "args_template": ["if=/dev/zero", "of={dest}", "bs=1", "count=1"],
      "params": {
        "dest": {"type": "workspace_path"}
      },
      "description": "Integration probe: write one byte to a workspace_path"
    },
    "ws_write_recursive": {
      "command": "dd",
      "args_template": ["if=/dev/zero", "of={dest}", "bs=1", "count=1"],
      "params": {
        "dest": {"type": "workspace_path"}
      },
      "allowed_flags": ["--recursive"],
      "description": "Integration probe: workspace_path with a scope-expander flag"
    },
    "git_add": {
      "command": "git",
      "args_template": ["add", "{paths}"],
      "params": {
        "paths": {"type": "array", "optional": true, "items": {"type": "string"}}
      },
      "allowed_flags": ["-u", "--update", "-A", "--all", "--pathspec-from-file", "--pathspec-file-nul"],
      "description": "Stage changes (path_deny guarded)"
    }
  }
}
EOF
    # Allow the config
    "$BINARY" config allow "$PROJECT_ID"
}

log_pass() {
    echo -e "${GREEN}✓${NC} $1"
    ((PASSED++))
}

log_fail() {
    echo -e "${RED}✗${NC} $1"
    echo "  Expected: $2"
    echo "  Got: $3"
    ((FAILED++))
}

# Build if needed
if [[ ! -f "$BINARY" ]]; then
    echo "Building binary..."
    (cd "$PROJECT_ROOT" && just build)
fi

# Setup daemon config with test port
echo "Setting up daemon config..."
setup_daemon_config

# Setup test token before starting daemon
echo "Setting up test token..."
setup_test_token

# Setup project config
echo "Setting up project config..."
setup_project_config

# Start daemon
echo "Starting daemon on port $PORT..."
"$BINARY" &
DAEMON_PID=$!
sleep 1

# Verify daemon is running
if ! kill -0 "$DAEMON_PID" 2>/dev/null; then
    echo "Failed to start daemon"
    exit 1
fi

echo ""
echo "Running scenario tests..."
echo ""

# Test helper for operation protocol
test_operation() {
    local name="$1"
    local request="$2"
    local expected_exit_code="$3"
    local expected_pattern="$4"

    local response
    response=$(echo "$request" | nc -w 5 localhost $PORT 2>/dev/null || echo '{"error":"connection failed"}')

    local actual_exit_code
    actual_exit_code=$(echo "$response" | python3 -c "import sys,json; print(json.load(sys.stdin).get('exit_code', -1))" 2>/dev/null || echo "-1")

    if [[ "$actual_exit_code" == "$expected_exit_code" ]]; then
        if [[ -n "$expected_pattern" ]]; then
            if echo "$response" | grep -q "$expected_pattern"; then
                log_pass "$name"
            else
                log_fail "$name" "pattern '$expected_pattern'" "$response"
            fi
        else
            log_pass "$name"
        fi
    else
        log_fail "$name" "exit_code=$expected_exit_code" "exit_code=$actual_exit_code ($response)"
    fi
}

# Test helper that passes if command was executed (not denied by cmd2host)
# Used for tests where actual command may fail due to CI environment limitations
test_operation_executed() {
    local name="$1"
    local request="$2"

    local response
    response=$(echo "$request" | nc -w 5 localhost $PORT 2>/dev/null || echo '{"error":"connection failed"}')

    local denied_reason
    denied_reason=$(echo "$response" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('denied_reason') or '')" 2>/dev/null || echo "error")

    if [[ -z "$denied_reason" ]]; then
        log_pass "$name"
    else
        log_fail "$name" "command to be executed (denied_reason=null)" "denied_reason=$denied_reason ($response)"
    fi
}

# Test helper for list_operations
test_list_operations() {
    local name="$1"
    local request="$2"
    local expected_pattern="$3"

    local response
    response=$(echo "$request" | nc -w 5 localhost $PORT 2>/dev/null || echo '{"error":"connection failed"}')

    if echo "$response" | grep -q "$expected_pattern"; then
        log_pass "$name"
    else
        log_fail "$name" "pattern '$expected_pattern'" "$response"
    fi
}

# =====================
# Operation tests
# =====================

# Test: gh_version (allowed operation, no params)
test_operation \
    "gh_version (allowed operation)" \
    '{"operation":"gh_version","params":{},"token":"'"$TEST_TOKEN"'"}' \
    "0" \
    "gh version"

# Test: gh_pr_list with repo injection from token
# Uses test_operation_executed because actual gh command may fail in CI (no GH_TOKEN inherited)
test_operation_executed \
    "gh_pr_list with repo injection (executed)" \
    '{"operation":"gh_pr_list","params":{},"flags":["--limit=1"],"token":"'"$TEST_TOKEN"'"}'

# Test: gh_pr_view with valid params (may fail in CI due to API permissions, but should not be denied)
test_operation_executed \
    "gh_pr_view with valid params (executed)" \
    '{"operation":"gh_pr_view","params":{"number":11},"token":"'"$TEST_TOKEN"'"}'

# Test: operation not in allowed_operations
test_operation \
    "operation not in allowed_operations (denied)" \
    '{"operation":"git_status","params":{},"token":"'"$TEST_TOKEN"'"}' \
    "1" \
    "Unknown operation"

# Test: git add --pathspec-from-file with explicit safe path is denied
# unconditionally when path_deny is configured (the pathspec source is
# read from a file that the daemon cannot enforce path_deny against).
test_operation \
    "git add --pathspec-from-file with explicit paths (denied)" \
    '{"operation":"git_add","params":{"paths":["src/main.go"]},"flags":["--pathspec-from-file=paths.txt"],"token":"'"$TEST_TOKEN"'"}' \
    "1" \
    "pathspec source cannot be enforced"

# Test: git add --pathspec-from-file with no paths is also denied.
test_operation \
    "git add --pathspec-from-file without paths (denied)" \
    '{"operation":"git_add","params":{},"flags":["--pathspec-from-file=paths.txt"],"token":"'"$TEST_TOKEN"'"}' \
    "1" \
    "pathspec source cannot be enforced"

# Test: invalid params (number below min)
test_operation \
    "invalid params (number below min)" \
    '{"operation":"gh_pr_view","params":{"number":0},"token":"'"$TEST_TOKEN"'"}' \
    "1" \
    "below minimum"

# Test: disallowed flag
test_operation \
    "disallowed flag" \
    '{"operation":"gh_pr_list","params":{},"flags":["--web"],"token":"'"$TEST_TOKEN"'"}' \
    "1" \
    "not allowed"

# Test: unknown operation
test_operation \
    "unknown operation" \
    '{"operation":"unknown_op","params":{},"token":"'"$TEST_TOKEN"'"}' \
    "1" \
    "Unknown operation"

# =====================
# workspace_path staging tests
# =====================

# Test: ws_write places the child's output at the workspace-relative path,
# proving the staging pipeline allocated → wrote → finalized end to end.
WS_PROBE_PATH="$PROJECT_ROOT/test/host/scratch/probe.bin"
rm -f "$WS_PROBE_PATH"
test_operation \
    "workspace_path staging places file at final path" \
    '{"operation":"ws_write","params":{"dest":"test/host/scratch/probe.bin"},"token":"'"$TEST_TOKEN"'"}' \
    "0" \
    '"stdout"'

if [[ -f "$WS_PROBE_PATH" ]]; then
    log_pass "workspace_path staging final path exists"
else
    log_fail "workspace_path staging final path exists" "$WS_PROBE_PATH present" "missing"
fi

# The staging root should have been cleaned up by the finalize step.
if [[ ! -e "$PROJECT_ROOT/.cmd2host-staging" ]] || [[ -z "$(ls -A "$PROJECT_ROOT/.cmd2host-staging" 2>/dev/null || true)" ]]; then
    log_pass "workspace_path staging root cleaned after finalize"
else
    log_fail "workspace_path staging root cleaned after finalize" "staging root absent or empty" "residual entries"
fi

# Test: workspace_path operation with a scope-expander flag is rejected
# before the child runs.
test_operation \
    "workspace_path with --recursive flag rejected" \
    '{"operation":"ws_write_recursive","params":{"dest":"test/host/scratch/should-not-exist.bin"},"flags":["--recursive"],"token":"'"$TEST_TOKEN"'"}' \
    "1" \
    "single-foreground-file output only"

if [[ -e "$PROJECT_ROOT/test/host/scratch/should-not-exist.bin" ]]; then
    log_fail "workspace_path scope-expander leaves no file" "no file" "present"
else
    log_pass "workspace_path scope-expander leaves no file"
fi

# =====================
# list_operations tests
# =====================

test_list_operations \
    "list_operations returns available ops" \
    '{"list_operations":true,"token":"'"$TEST_TOKEN"'"}' \
    "gh_version"

# Test: list_operations with prefix filter
test_list_operations \
    "list_operations with prefix 'gh_pr' returns only gh_pr operations" \
    '{"list_operations":true,"prefix":"gh_pr","token":"'"$TEST_TOKEN"'"}' \
    "gh_pr_list"

# Test: list_operations with prefix filter excludes non-matching
test_list_operations_excludes() {
    local name="$1"
    local request="$2"
    local excluded_pattern="$3"

    local response
    response=$(echo "$request" | nc -w 5 localhost $PORT 2>/dev/null || echo '{"error":"connection failed"}')

    if echo "$response" | grep -q "$excluded_pattern"; then
        log_fail "$name" "pattern '$excluded_pattern' to be excluded" "$response"
    else
        log_pass "$name"
    fi
}

test_list_operations_excludes \
    "list_operations with prefix 'gh_pr' excludes gh_version" \
    '{"list_operations":true,"prefix":"gh_pr","token":"'"$TEST_TOKEN"'"}' \
    "gh_version"

# Test: list_operations with non-matching prefix returns empty
test_list_operations_empty() {
    local name="$1"
    local request="$2"

    local response
    response=$(echo "$request" | nc -w 5 localhost $PORT 2>/dev/null || echo '{"error":"connection failed"}')

    local op_count
    # Handle both null and empty array: null -> 0, [] -> 0
    op_count=$(echo "$response" | python3 -c "import sys,json; ops=json.load(sys.stdin).get('operations'); print(0 if ops is None else len(ops))" 2>/dev/null || echo "-1")

    if [[ "$op_count" == "0" ]]; then
        log_pass "$name"
    else
        log_fail "$name" "0 operations" "$op_count operations ($response)"
    fi
}

test_list_operations_empty \
    "list_operations with non-matching prefix returns empty" \
    '{"list_operations":true,"prefix":"docker","token":"'"$TEST_TOKEN"'"}'

# =====================
# Authentication tests
# =====================

test_operation \
    "auth failure - no token" \
    '{"operation":"gh_version","params":{}}' \
    "1" \
    "Authentication failed"

test_operation \
    "auth failure - wrong token" \
    '{"operation":"gh_version","params":{},"token":"wrong-token"}' \
    "1" \
    "Authentication failed"

# Summary
echo ""
echo "================================"
echo -e "Passed: ${GREEN}$PASSED${NC}"
echo -e "Failed: ${RED}$FAILED${NC}"
echo "================================"

if [[ $FAILED -gt 0 ]]; then
    exit 1
fi
